apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: siibra-api
    flavor: prod
    queue: 0.3.14.siibraapi.core
    queue_name: core
    role: worker
    siibraapi_version: "0.3.14"
  name: api-worker-deployment-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siibra-api
      flavor: prod
      role: worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: siibra-api
        flavor: prod
        role: worker
    spec:
      containers:
      - args:
        - -A
        - api.worker.app
        - worker
        - -Q
        - 0.3.14.siibraapi.core
        - -O
        - fair
        command:
        - celery
        envFrom:
        - configMapRef:
            name: siibra-api-common
        image: docker-registry.ebrains.eu/siibra/siibra-api:0.3.14-worker
        name: siibra-api-prod-worker
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            cpu: "400m"
            memory: 2Gi
          requests:
            cpu: "200m"
            memory: 1Gi
        volumeMounts:
        - mountPath: /siibra-api-volume
          name: data-volume
        - mountPath: /siibra_api_logs
          name: log-volume
      restartPolicy: Always
      volumes:
      - name: log-volume
        persistentVolumeClaim:
          claimName: log-volume-claim
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-volume-claim
